# Generated by Django 4.1.7 on 2023-03-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='User Name')),
                ('user_emain', models.EmailField(max_length=254, verbose_name='User Email')),
                ('user_phon', models.CharField(max_length=50, verbose_name='User Phon')),
                ('user_review', models.TextField(verbose_name='User Review')),
            ],
        ),
    ]
