# Generated by Django 4.1.7 on 2023-03-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_emain',
            new_name='user_email',
        ),
    ]
