# Generated by Django 4.1.7 on 2023-03-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_emain_contact_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('product_price', models.PositiveBigIntegerField(verbose_name='Product Price')),
                ('product_image', models.ImageField(upload_to='', verbose_name='Product Image')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['id']},
        ),
    ]
