# Generated by Django 4.1.7 on 2023-03-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contact_options_product_product_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Product Data'),
        ),
    ]
