# Generated by Django 4.1.7 on 2023-03-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_about',
            field=models.TextField(blank=True, default='', verbose_name='Product About'),
        ),
    ]
