# Generated by Django 4.1.7 on 2023-03-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_product_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date']},
        ),
    ]
